baseurl = "/"
languageCode = "en-us"
title = "Diogo Felix"
subtitle = "T-shaped Developer"
theme = "frugal"
github = "https://github.com/onlurking"
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/posts/:slug/"
    note = "/notes/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 2
[[menu.main]]
    name = "Now"
    url = "/now/"
    weight = 2
[[menu.main]]
    name = "Feed"
    url = "/index.xml"

[params]
    description = "A website built through Hugo and blogdown."
